spring.application.name=Stock-Screener
server.address=127.0.0.1
server.port=8080
spring.docker.compose.enabled=false
# H2 in-memory DB config
spring.redis.port=6379
spring.redis.host=127.0.0.1
spring.code.max-in-memory-size=16MB
# Upstox OAuth / token settings
upstox.client-id=${UPSTOX_CLIENT_ID:45f9a51e-b32b-44c4-9db4-9060a14c9b45}
upstox.client-secret=${UPSTOX_CLIENT_SECRET:1l443mz77b}
upstox.redirect-uri=${UPSTOX_REDIRECT_URI:http://localhost:8080/auth/callback}
upstox.authorize-url=https://api.upstox.com/v2/login/authorization/dialog
upstox.token-url=https://api.upstox.com/v2/login/authorization/token
upstox.authorizeweb-url=https://api.upstox.com/v3/feed/market-data-feed/authorize
spring.mvc.converters.preferred-json-mapper=gson
# R2DBC connection
spring.r2dbc.url=r2dbc:postgresql://aws-1-ap-southeast-1.pooler.supabase.com:5432/postgres?sslMode=require
spring.r2dbc.username=postgres.xykgtrhpiykwfkjxbkos
spring.r2dbc.password=Ravi1234@
